### ISSUE TITLE
Optimise caching

### ISSUE THREAD

**Issue by ZooeyMiller** [oliverjam/bookmarkd#24]
we need to clone the stream of our fetch requests for the epubs so that we can feed one stream straight the the browser and one stream directly into the cache otherwise "the body will already be consumed" :metal:

- [ ] optimise pre-caching
- [ ] set cache storage when book is opened without interrupting opening of book

**Comment by oliverjam** [comment]
sw-precache actually takes a `runtimeCaching` options object that lets us configure any runtime caching we like. So this should all happen automatically once that is set-up.
