### ISSUE TITLE
Populate books background array

### ISSUE THREAD

**Issue by ZooeyMiller** [oliverjam/bookmarkd#61]
We are basing the background image of hte book cards on the first letter of the Author's name, so we need 26 backgounds to account for each potential author's name.

**Comment by oliverjam** [comment]
I'm not sure this is feasible tbh. I just went through Hero Patterns and only found 6 decent ones that I liked enough to use. It might have to just be randomish.

The patterns are in here if you want them: http://codepen.io/oliverjam/pen/LyQeLe

**Comment by ZooeyMiller** [comment]
Lol I just did it

**Comment by ZooeyMiller** [comment]
I just picked 26 out so that there are 26 unique ones, nbd if you wanna take them out, they're there if you want them though
